services:
  lofiplay:
    image: ghcr.io/yesmohsen/lofiplay:latest
    container_name: lofiplay
    pull_policy: always
    restart: unless-stopped
    ports:
      - "6001:6001"
    volumes:
      - lofiplay-audio:/app/static/audio
      - lofiplay-bg:/app/static/backgrounds

volumes:
  lofiplay-audio:
  lofiplay-bg:
